name: CI Pipeline

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: 🧪 Lint • Type Check • Unit Test (${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f uv.lock ]; then
            pip install uv
            uv sync --all-extras --dev
          elif [ -f pyproject.toml ]; then
            pip install .[dev] || pip install -e .
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install ruff mypy pytest pytest-cov

      - name: Ruff (Lint)
        run: |
          ruff check .
          ruff format --check .

      - name: MyPy (Type Check)
        run: |
          mypy --ignore-missing-imports --install-types --non-interactive .

      - name: Run Unit Tests
        env:
          OPENAI_API_KEY: "dummy-key" # avoid using real secret for unit tests
        run: |
          pytest -q --disable-warnings --maxfail=1 --cov=. --cov-report=xml

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  integration:
    name: 🔐 Integration Tests (Uses Secrets)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only on main
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f uv.lock ]; then
            pip install uv
            uv sync --all-extras --dev
          elif [ -f pyproject.toml ]; then
            pip install .[dev] || pip install -e .
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install pytest

      - name: Run Integration Tests (with secret)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PHONENIX_ENDPOINT: ${{ secrets.PHONENIX_ENDPOINT }}
        run: |
          pytest tests/integration -q --disable-warnings || echo "Integration tests skipped or failed gracefully"
