name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Sync dependencies with uv (locked)
        run: |
          uv sync --frozen
          uv pip install pytest
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/Notebooks
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PHONENIX_ENDPOINT: ${{ secrets.PHONENIX_ENDPOINT }}
        run: |
          uv run pytest -q
